/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TransformationCase, ProjectStatus, ProjectDecision, TshirtSize, AIGovernanceCase, AIGovernanceDecision } from './types.ts';

export const DEMO_GOVERNANCE_CASES: AIGovernanceCase[] = [
  {
    id: "demo1",
    created_at: "2025-04-01T09:00:00.000Z",
    decided_at: "2025-04-03T09:00:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: AIGovernanceDecision.APPROVED,
    approved_date: "2025-04-03",
    next_review_date: "2025-10-03",
    registry_status: "active",
    requestor_name: "Sofia Papadopoulou",
    requestor_department: "AML",
    initiative_title: "AML Transaction Pattern Analyser",
    initiative_description: "Uses Gemini to analyse transaction patterns and surface suspicious behaviour for human review by AML analysts.",
    use_type: "team tool",
    intended_purpose: "Surface suspicious transactions for analyst review",
    users_scope: "department",
    markets_affected: "All markets",
    data_types: "AML / KYC data, Financial / payment data",
    system_integrations: "Internal transaction database, Jira",
    ai_tool: "Gemini",
    human_in_loop: "always",
    regulated_process: "Yes — AML monitoring",
    bias_risk: "No",
    strategic_driver: "Shield Betano",
    deadline: "Q2 2025 regulatory audit",
    additional_context: "",
    tier: "T3",
    tier_score: 14,
    dpo_approved: true,
    security_approved: true,
    architecture_approved: true,
    flags: [],
    assessment_notes: "Fully compliant. Human always in loop. DPO signed off."
  },
  {
    id: "demo2",
    created_at: "2025-04-10T11:00:00.000Z",
    decided_at: "2025-04-12T09:00:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: AIGovernanceDecision.APPROVED,
    approved_date: "2025-04-12",
    next_review_date: "2026-04-12",
    registry_status: "active",
    requestor_name: "Nikos Georgiou",
    requestor_department: "CRM",
    initiative_title: "CRM Email Personalisation Agent",
    initiative_description: "Claude Enterprise generates personalised email content for CRM campaigns based on player segment data.",
    use_type: "automated workflow",
    intended_purpose: "Generate personalised campaign emails at scale",
    users_scope: "department",
    markets_affected: "English (UK), German, Romanian",
    data_types: "Behavioral / gaming data, Internal business data",
    system_integrations: "CRM platform, Google Workspace",
    ai_tool: "Claude Enterprise",
    human_in_loop: "always",
    regulated_process: "No",
    bias_risk: "Yes — player segmentation",
    strategic_driver: "Hey Betano",
    deadline: "Before Q3 campaign season",
    additional_context: "",
    tier: "T2",
    tier_score: 7,
    dpo_approved: false,
    security_approved: false,
    architecture_approved: false,
    flags: ["Bias review completed — segmentation based on activity not demographics"],
    assessment_notes: "Approved with note: bias review satisfactory."
  },
  {
    id: "demo3",
    created_at: "2025-04-20T14:00:00.000Z",
    decided_at: null,
    status: ProjectStatus.REVIEW,
    decision: null,
    registry_status: "pending",
    requestor_name: "Maria Ionescu",
    requestor_department: "Product",
    initiative_title: "Responsible Gambling Early Warning System",
    initiative_description: "AI model to detect early signs of problem gambling behaviour and trigger intervention workflows.",
    use_type: "AI agent",
    intended_purpose: "Detect and flag at-risk players for RG team review",
    users_scope: "multi-dept",
    markets_affected: "All markets",
    data_types: "Behavioral / gaming data, Player PII",
    system_integrations: "Player activity database, RG platform, Slack",
    ai_tool: "Gemini",
    human_in_loop: "sometimes",
    regulated_process: "Yes — Responsible Gambling",
    bias_risk: "Yes — decisions affect players based on behaviour profile",
    strategic_driver: "Shield Betano",
    deadline: "Regulatory requirement by Q4",
    additional_context: "",
    approved_date: "",
    next_review_date: "",
    tier: "T3",
    tier_score: 16,
    dpo_approved: false,
    security_approved: false,
    architecture_approved: false,
    flags: ["DPO review pending", "Human oversight policy needs clarification — 'sometimes' not sufficient for RG", "Architecture review not started"],
    assessment_notes: ""
  },
  {
    id: "demo4",
    created_at: "2025-04-25T10:00:00.000Z",
    decided_at: null,
    status: ProjectStatus.PENDING,
    decision: null,
    registry_status: "pending",
    requestor_name: "Dimitris Alexiou",
    requestor_department: "Finance",
    initiative_title: "Finance Report Summarisation Tool",
    initiative_description: "Uses Claude Enterprise to summarise monthly financial reports into executive briefings.",
    use_type: "personal use",
    intended_purpose: "Summarise reports faster for internal review",
    users_scope: "team",
    markets_affected: "Internal only",
    data_types: "Internal business data",
    system_integrations: "Google Drive",
    ai_tool: "Claude Enterprise",
    human_in_loop: "always",
    regulated_process: "No",
    bias_risk: "No",
    strategic_driver: "Core Betano",
    deadline: "No hard deadline",
    additional_context: "",
    approved_date: "",
    next_review_date: "",
    tier: "T2",
    tier_score: 4,
    dpo_approved: false,
    security_approved: false,
    architecture_approved: false,
    flags: [],
    assessment_notes: ""
  },
  {
    id: "demo5",
    created_at: "2025-04-28T16:00:00.000Z",
    decided_at: "2025-04-30T10:00:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: AIGovernanceDecision.REJECTED,
    registry_status: "rejected",
    requestor_name: "Elena Vasquez",
    requestor_department: "Marketing",
    initiative_title: "Social Media Content Generator",
    initiative_description: "Wanted to use ChatGPT API to generate social media posts using player engagement data.",
    use_type: "automated workflow",
    intended_purpose: "Generate social content at scale",
    users_scope: "department",
    markets_affected: "Latin America markets",
    data_types: "Behavioral / gaming data, Player PII",
    system_integrations: "Social media APIs, CRM",
    ai_tool: "ChatGPT (OpenAI API)",
    human_in_loop: "sometimes",
    regulated_process: "No",
    bias_risk: "No",
    strategic_driver: "Hey Betano",
    deadline: "Upcoming campaign",
    additional_context: "",
    approved_date: "",
    next_review_date: "",
    tier: "T3",
    tier_score: 12,
    dpo_approved: false,
    security_approved: false,
    architecture_approved: false,
    flags: ["Unapproved AI tool — ChatGPT/OpenAI API not approved at Kaizen", "Player PII cannot be sent to non-approved external model", "Must use Gemini or Claude Enterprise"],
    assessment_notes: "Rejected: unapproved tool used with player PII. Requestor advised to resubmit using Claude Enterprise or Gemini with appropriate data controls."
  }
];

export const DEMO_DATA: TransformationCase[] = [
  {
    id: "1714900000001",
    created_at: "2025-05-01T10:00:00.000Z",
    decided_at: null,
    status: ProjectStatus.PENDING,
    decision: null,
    project_title: "Automated Customer Verification",
    requestor_name: "Elena Katsi",
    requestor_department: "Compliance",
    department: "Compliance",
    teams_involved: "Compliance, KYC, Platform",
    markets_affected: "Greece, Cyprus",
    duration: "1-3 months",
    tier: "T2",
    tshirt: TshirtSize.M,
    problem_statement: "Manual verification of Greek IDs is causing backlogs and slowing down account activations during peak events.",
    expected_outcome: "Automated verification for 90% of Greek IDs with < 5min turnaround.",
    volume_per_month: "1200",
    hours_per_case: "0.5",
    team_profile: "Senior, Greece",
    annual_fte_cost: "48600",
    annual_hours: "5424",
    fte_saving_est: "3.15",
    soft_benefits: "Faster onboarding, Reduced human error, Regulatory compliance",
    strategic_driver: "Shield Betano",
    deadline: "2025-09-01",
    impl_cost: "22000",
    payback_months: "5",
    flags: ["Integration with 3rd party API unconfirmed"],
    score_problem: 0,
    score_benefit: 0,
    score_strategic: 0,
    score_feasibility: 0,
    score_urgency: 0,
    score_data: 0,
    assessment_notes: ""
  },
  {
    id: "1714900000002",
    created_at: "2025-05-02T11:30:00.000Z",
    decided_at: "2025-05-03T09:00:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: ProjectDecision.GO,
    project_title: "AI Personalization Engine",
    requestor_name: "Marco Silva",
    requestor_department: "Marketing",
    department: "Marketing",
    teams_involved: "Marketing, Data Science, CRM",
    markets_affected: "Romania, Brazil",
    duration: "3+ months",
    tier: "T3",
    tshirt: TshirtSize.XL,
    problem_statement: "Generic marketing banners leading to low conversion rates in Romanian market.",
    expected_outcome: "15% increase in offer uptake via real-time segment-based banners.",
    volume_per_month: "5000",
    hours_per_case: "0.2",
    team_profile: "Mid, Romania",
    annual_fte_cost: "35000",
    annual_hours: "12000",
    fte_saving_est: "6.98",
    soft_benefits: "Higher GGR, Improved retention, Personalization",
    strategic_driver: "Hey Betano",
    deadline: "No hard deadline",
    impl_cost: "15000",
    payback_months: "5",
    flags: [],
    score_problem: 5,
    score_benefit: 4,
    score_strategic: 5,
    score_feasibility: 4,
    score_urgency: 3,
    score_data: 5,
    assessment_notes: "Strong strategic alignment. High ROI."
  },
  {
    id: "1714900000003",
    created_at: "2025-04-25T14:20:00.000Z",
    decided_at: "2025-05-01T16:45:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: ProjectDecision.NOGO,
    project_title: "Legacy Report Migration",
    requestor_name: "David Smith",
    requestor_department: "Finance",
    department: "Finance",
    teams_involved: "Finance, Data Engine",
    markets_affected: "Corporate",
    duration: "3+ months",
    tier: "T2",
    tshirt: TshirtSize.L,
    problem_statement: "Moving 400 spreadsheet-based reports to the new BI tool without prior rationalization.",
    expected_outcome: "Single source of truth for 50 rationalized reports in BI tool.",
    volume_per_month: "400",
    hours_per_case: "8",
    team_profile: "Mid, Greece",
    annual_fte_cost: "250000",
    annual_hours: "38400",
    fte_saving_est: "22.3",
    soft_benefits: "Fewer spreadsheets",
    strategic_driver: "Betano Republic",
    deadline: "Urgent cleanup",
    impl_cost: "80000",
    payback_months: "4",
    flags: ["No benefit from migrating useless reports", "High risk of garbage-in/garbage-out"],
    score_problem: 2,
    score_benefit: 1,
    score_strategic: 1,
    score_feasibility: 3,
    score_urgency: 4,
    score_data: 1,
    assessment_notes: "Rejected due to lack of strategic value. Need rationalization first."
  },
  {
    id: "1714900000004",
    created_at: "2025-05-03T10:15:00.000Z",
    decided_at: null,
    status: ProjectStatus.REVIEW,
    decision: null,
    project_title: "Market Expansion Research Tool",
    requestor_name: "Yiannis P.",
    requestor_department: "Sportsbook",
    department: "Sportsbook",
    teams_involved: "Sportsbook, Trading",
    markets_affected: "New Markets (LATAM)",
    duration: "1-3 months",
    tier: "T2",
    tshirt: TshirtSize.M,
    problem_statement: "Manual scraping of competitor odds across 5 newly regulated markets.",
    expected_outcome: "Real-time odds mapping for top 10 competitors across CABA/PBA.",
    volume_per_month: "150",
    hours_per_case: "4",
    team_profile: "Senior, Malta",
    annual_fte_cost: "75000",
    annual_hours: "7200",
    fte_saving_est: "4.18",
    soft_benefits: "Speed to market, Competitive edge",
    strategic_driver: "Core Betano",
    deadline: "2025-12-01",
    impl_cost: "12000",
    payback_months: "2",
    flags: ["Legal constraints on scraping in specific regions unverified"],
    score_problem: 4,
    score_benefit: 3,
    score_strategic: 4,
    score_feasibility: 2,
    score_urgency: 3,
    score_data: 4,
    assessment_notes: "Promising but legal risks need checking."
  }
];
