/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { UnifiedCase, ProjectStatus, ProjectDecision, TshirtSize, CaseType } from './types';

export const UNIFIED_DEMO_DATA: UnifiedCase[] = [
  {
    id: "demo-ai-1",
    userId: "demo-user-1",
    created_at: "2025-05-01T09:00:00.000Z",
    decided_at: "2025-05-03T10:00:00.000Z",
    status: ProjectStatus.DECIDED,
    decision: ProjectDecision.GO,
    case_type: CaseType.AI,
    tier: "T3",
    requestor_name: "Sofia Papadopoulou",
    requestor_department: "AML",
    requestor_email: "sofia.p@kaizengaming.com",
    project_title: "AML Transaction Pattern Analyser",
    problem_statement: "Manual review of high-volume transaction alerts is creating substantial backlog and potential regulatory risk.",
    expected_outcome: "AI-assisted triage surfacing only high-probability suspicious patterns for human focus.",
    markets_affected: "All Markets",
    strategic_driver: "Shield Betano",
    deadline: "Q4 2025 Audit",
    flags: ["Regulated Process"],
    assessment_notes: "Strong compliance fit. Reduces risk of missed alerts.",
    ai_tool: "Gemini / Vertex AI",
    use_type: "Department Tool",
    intended_purpose: "Automated alert triage",
    users_scope: "AML Team (50 users)",
    data_types: "Transaction logs, KYC data",
    system_integrations: "Internal Data Lake, Case Management System",
    human_in_loop: "Always (Final decision by human)",
    regulated_process: "Yes (Financial Crime Compliance)",
    tier_score: 14,
    score_problem: 5, score_benefit: 4, score_strategic: 5, score_feasibility: 4, score_urgency: 3, score_data: 5,
    dpo_approved: true,
    security_approved: true,
    architecture_approved: true,
    registry_status: 'active'
  },
  {
    id: "demo-project-1",
    userId: "demo-user-2",
    created_at: "2025-05-02T11:00:00.000Z",
    decided_at: null,
    status: ProjectStatus.REVIEW,
    decision: null,
    case_type: CaseType.PROJECT,
    tier: "T2",
    requestor_name: "Marco Silva",
    requestor_department: "Marketing",
    project_title: "Market Playbook Localisation",
    problem_statement: "Inefficient manual translation and formatting of marketing playbooks for new market entries.",
    expected_outcome: "Standardized digital playbooks with automated region mapping.",
    markets_affected: "Brazil, Mexico, Colombia",
    strategic_driver: "Betano Republic",
    deadline: "Summer Season Start",
    flags: [],
    assessment_notes: "Core operational improvement for LATAM expansion.",
    teams_involved: "Marketing, Local Content, Operations",
    duration: "2-3 months",
    tshirt: TshirtSize.M,
    volume_per_month: "10 playbooks",
    hours_per_case: "40",
    team_profile: "Mid, Brazil",
    annual_fte_cost: "52000",
    annual_hours: "4800",
    fte_saving_est: "2.8",
    impl_cost: "15000",
    payback_months: "4",
    score_problem: 4, score_benefit: 4, score_strategic: 5, score_feasibility: 4, score_urgency: 2, score_data: 3
  },
  {
    id: "demo-hybrid-1",
    userId: "demo-user-3",
    created_at: "2025-05-04T14:00:00.000Z",
    decided_at: null,
    status: ProjectStatus.PENDING,
    decision: null,
    case_type: CaseType.HYBRID,
    tier: "T3",
    requestor_name: "Yiannis P.",
    requestor_department: "Sportsbook",
    project_title: "Intelligent Odds Scraping & Mapping",
    problem_statement: "Manual tracking of competitor odds in fast-moving LATAM markets is non-scalable.",
    expected_outcome: "Automated system that scrapes, maps via AI, and flags outliers for traders.",
    markets_affected: "Argentina, Peru, Chile",
    strategic_driver: "Core Betano",
    deadline: "Basketball Season Off",
    flags: ["Custom Crawler Req", "Data Protection Review"],
    assessment_notes: "",
    teams_involved: "Sportsbook, Trading, Data Engine",
    duration: "4 months",
    tshirt: TshirtSize.L,
    volume_per_month: "500 markets/day",
    hours_per_case: "0.25",
    team_profile: "Senior, Greece",
    annual_fte_cost: "110000",
    annual_hours: "15000",
    fte_saving_est: "8.7",
    impl_cost: "45000",
    payback_months: "5",
    ai_tool: "Custom Agent + Claude Enterprise",
    use_type: "Automated Workflow",
    intended_purpose: "Automate market intelligence",
    users_scope: "Trading Floor",
    data_types: "Market Data, Competitor Feeds",
    human_in_loop: "Sometimes (High confidence auto-acts)",
    tier_score: 12,
    score_problem: 4, score_benefit: 5, score_strategic: 4, score_feasibility: 3, score_urgency: 4, score_data: 4
  }
];
